spring:
  datasource:
    url: jdbc:mysql://172.16.94.13:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 172.16.94.13
    port: 6379
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
mybatis:
  type-aliases-package: com.galaxy.rcache.entity
  mapper-locations: classpath:mapper/*.xml
